<?php echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
<h2>Login</h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login'));
$form->setAttribute('class', 'form-signin');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
	<input class="form-control" name="usernameOrEmail" type="text" placeholder="Username or email" value="">
</div>
<div class="form-group">
	<input class="form-control" name="password" type="password" placeholder="Password" value="">
</div>
<div class="checkbox">
	<label>
		<span>Remember me?</span>
		<input type="hidden" name="rememberme" value="0">
		<input type="checkbox" name="rememberme" value="1">
	</label>	
</div>
<button type="submit" class="btn btn-success">Login</button>
<?
echo $this->form()->closeTag();
?>
<br/>
<p>
	<a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Sign up'); ?></a> |  
	<a href="<?php echo $this->url('forgotten-password');?>"><?php echo $this->translate('Forgot your password?'); ?></a>
</p>
<br/>
<?php echo '<div style="font-size: 20px; color: red;">' . $this->messages . '</div>'; ?>
