<?php if($this->navMenu == true){ ?>
<ul class="nav navbar-nav navbar-right">
<?php
	if (!$user = $this->identity()) {
?>
	<li><a class="btn btn-primary btn-xs" href="<?php echo $this->url('login');?>"><?php echo $this->translate('Log in'); ?></a></li>
	<!--<li><a class="btn btn-primary btn-xs" href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Sign up'); ?></a></li>-->
<?php
	}else{
?>
    <li id="fat-menu" class="dropdown">
      <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">
		<?php echo $this->gravatar($user->getEmail()) ?>
		<?php echo $user->getUsername(); ?>
		 <b class="caret"></b></a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
      	<!--
        <li role="presentation"><a role="menuitem" tabindex="-1" href="http://twitter.com/fat">Action</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="http://twitter.com/fat">Another action</a></li>
       -->
        <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('editProfile');?>"><?php echo $this->translate('Edit Profile'); ?></a></li>
        <li role="presentation" class="divider"></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('logout');?>"><?php echo $this->translate('Logout'); ?></a></li>
      </ul>
    </li>

<?php } ?>
</ul>
<?php } ?>