<?php
 $title = $this->translate('Add new stitch pattern');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('stitchpattern', array('action' => 'add')));
 $form->prepare();
?>
<p><span class="glyphicon glyphicon-picture"></span> <b><?=$this->translate('Load an image');?></b> <?=$this->translate('drag and drop the file onto the grid below. It handles black and white images best.');?></p>
<p><span class="glyphicon glyphicon-move"></span> <b><?=$this->translate('Zoom and pan');?></b> <?=$this->translate('hold down shift while scrolling or dragging (experimental).');?></p>
<div id="stitchCanvasContainer"></div>
<?php
 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
?>
<script type="text/javascript" src="/js/kinetic-v4.7.2.min.js"></script>
<script type="text/javascript" src="/js/customUtils.js"></script>