<?php
 $title = $this->translate('Add new stitch pattern');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('stitchpattern', array('action' => 'add')));
 $form->prepare();

/*
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();

 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
 * */
?>
<!--
<input type="file" id="imageLoader" name="imageLoader"/> -->
<p><span class="glyphicon glyphicon-ok-sign"></span> <?=$this->translate('To draw from an image simply drag and drop the file onto the grid below.');?></p>
<div id="stitchCanvasContainer"></div>
<?php
 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
?>
<script type="text/javascript" src="/js/kinetic-v4.7.4.min.js"></script>
<script type="text/javascript" src="/js/customUtils.js"></script>