<?php
 $title = $this->translate('Add new stitch pattern');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('stitchpattern', array('action' => 'add')));
 $form->prepare();

/*
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
*/

 echo $this->form()->openTag($form);
 echo $this->formCollection($form);
 echo $this->form()->closeTag();
