<div class="container container-page">
 <?php

 $title = $this->translate('Delete stitch pattern');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><?=$this->translate('Are you sure that you want to delete'); ?>
     '<?php echo $this->escapeHtml($stitchpattern->title); ?>'?
 </p>
 <?php
 $url = $this->url('stitchpattern', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $stitchpattern->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>
</div>
