 <?php
 $title = $this->translate('Edit Stitch Pattern');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'stitchpattern',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();
?>
<p><span class="glyphicon glyphicon-picture"></span> <b><?=$this->translate('Load an image');?></b> <?=$this->translate('drag and drop the file onto the grid below. It handles black and white images best.');?></p>
<p><span class="glyphicon glyphicon-move"></span> <b><?=$this->translate('Zoom and pan');?></b> <?=$this->translate('hold down shift while scrolling or dragging (experimental).');?></p>
<div id="stitchCanvasContainer"></div>
<?php
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formHidden($form->get('shared'));
 echo $this->formHidden($form->get('stitches'));
 echo $this->formHidden($form->get('preview'));
 echo $this->formRow($form->get('title'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>
<script type="text/javascript" src="/js/kinetic-v4.7.4.min.js"></script>
<script type="text/javascript" src="/js/customUtils.js"></script>