<div class="container container-page">
	
 <?php
 $title = $this->translate('Edit Stitch Pattern');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'stitchpattern',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

?>
<!--
<input type="file" id="imageLoader" name="imageLoader"/>
-->
<p><span class="glyphicon glyphicon-ok-sign"></span> <?=$this->translate('Protip: you can drag and drop an image file onto the grid below.');?></p>
<div id="stitchCanvasContainer"></div>
<?php
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formHidden($form->get('stitches'));
 echo $this->formHidden($form->get('preview'));
 echo $this->formRow($form->get('title'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>
<script type="text/javascript" src="/js/kinetic-v4.7.4.min.js"></script>
<script type="text/javascript" src="/js/customUtils.js"></script>
</div>
