<?php
	$title = $this->translate('My Stitch Patterns');
	$this->headTitle($title);
?>
<div class="jumbotron">
	<div class="container">
		<h1><?= $this->translate('Machine knitting made easier'); ?></h1>
		<p><?= $this->translate('Design your own stitch patterns and turn them into beautiful knits with your'); ?> <a href=""><?=$this->translate('Brother 950i');?></a>.</p>
		<a class="btn btn-primary btn-lg" href="/signup">
			<?=$this->translate('Get started');?> »
		</a>
	</div>
</div>
<div class="container">
<h2><?=$this->translate('Public Patterns');?></h2>

<section class="list public cf">
<?php foreach ($stitchpatterns as $key=>$stitchpattern) { ?>
	<article>
		<div>
			<img src="<?php echo $this->escapeHtml($stitchpattern->preview);?>"/>
			<h4><?php echo $this->escapeHtml($stitchpattern->title);?></h4>

			<a class="btn btn-success btn-xs" href="<?php echo $this->url('stitchpattern',
				array('action'=>'convert', 'id' => $stitchpattern->id));?>">
				<?= $this->translate('Knit it'); ?> »
			</a>
		</div>
	</article>
<?php } ?>
</section>