<?php
	$title = $this->translate('My Stitch Patterns');
	$this->headTitle($title);
?>
<div class="jumbotron">
	<div class="container">
		<h1><?= $this->translate('Machine knitting made easier'); ?></h1>
		<p><?= $this->translate('Design your own stitch patterns and turn them into beautiful knits with your'); ?> <a target="_blank" href="http://wiki.london.hackspace.org.uk/view/Equipment/Knitting_Machine"><?=$this->translate('Brother 950i');?></a>.</p>
		<a class="btn btn-primary btn-lg" href="/signup">
			<?=$this->translate('Get started');?> »
		</a>
	</div>
</div>
<div class="container">
<h2><?=$this->translate('Public Patterns');?></h2>

<?php echo $this->partial('stitch-pattern/stitch-pattern/public_list.phtml', array('stitchpatterns' => $this->stitchpatterns)); ?>