<section class="list public cf">
<?php $iterated = false; foreach ($stitchpatterns as $key=>$stitchpattern) { $iterated = true; ?>
	<article>
		<div>
			<img src="/<?php echo $this->escapeHtml($stitchpattern->previewDir);?>"/>
			<h4><?php echo $this->escapeHtml($stitchpattern->title);?></h4>
			<p><a href="/u/<?php echo $this->escapeHtml($stitchpattern->username);?>"><?php echo $this->escapeHtml($stitchpattern->username);?></a> 
				<time><?= $this->TimeAgo()->getTime($stitchpattern->update_date); ?></time>
			</p>

			<a class="btn btn-success btn-xs" href="<?php echo $this->url('stitchpattern',
				array('action'=>'convert', 'id' => $stitchpattern->id));?>">
				<?= $this->translate('Knit it'); ?> »
			</a>
		</div>
	</article>
<?php } ?>
<?php if(!$iterated) :?>
	<article>
	<p><?=$this->translate('None available yet.');?></p>
	</article>
<?php endif; ?>
</section>