<div class="row">
<div class="col-md-1">
<?=$this->gravatar($this->user->getEmail()) ?>
</div>
<div class="col-md-11">
<h1><?=$this->user->getUsername()?></h1>
<p>joined <time><?= $this->TimeAgo()->getTime($this->user->getRegistrationDate()->format('Y-m-d H:i:s')); ?></time></p>
</div>
</div>
</div>

<div class="container">
<h3><?=$this->user->getUsername()?>'s public patterns</h3>
<?php echo $this->partial('stitch-pattern/stitch-pattern/public_list.phtml', array('stitchpatterns' => $this->sharedSP)); ?>
