<?php echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
<h2>Change email</h2>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('changeEmail'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('currentPassword'));
echo '<br />';
echo $this->formRow($form->get('newEmail'));
echo '<br />';
echo $this->formRow($form->get('newEmailConfirm'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<br/>
<?php echo '<div style="font-size: 20px; color: red;">' . $this->message . '</div>'; ?>
