<?php echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
<h2>Reset password</h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('forgotten-password'));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('usernameOrEmail'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<?php echo '<div style="font-size: 20px; color: red;">' . $this->message . '</div>'; ?>
