<h2>Sign up</h2>
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('registration'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo '<br />';

/* Choose to display displayName or firstName and lastName*/

/*echo $this->formRow($form->get('firstName'));
echo '<br />';
echo $this->formRow($form->get('lastName'));
echo '<br />';*/
echo $this->formRow($form->get('displayName'));
echo '<br />';
echo $this->formRow($form->get('email'));
echo '<br />';
echo $this->formRow($form->get('password'));
echo '<br />';
echo $this->formRow($form->get('passwordConfirm'));
echo '<br />';
echo '<div class="stdout">';
echo $this->formRow($form->get('captcha'));
echo '</div>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>
